import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import NavBar from '../comps/NavBar';
import TopBar from '../comps/TopBar';
import Article from '../comps/Article';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TopBar/>

        <Article
            articletitle="Why is the last name Nguyễn so popular?"
            articlelang="Vietnamese"
            articleimg="/Coco_Nguyen.svg"
            articletext="About 39% of Vietnamese people share the last name, Nguyễn.
            Why? Well, back in the feudal times, kings required people to change their last names to avoid punishment and as a sign of submission. 
            Families also changed their name to gain favours from the current dynastry. 
            The Nguyễn dynasty was the last dynasty so no new kings forced other families to change their names from Nguyễn."
            />

        <NavBar
          historybuttoncolor='#FC5F6C'
          historytextcolor='#FC5F6C'
       />

      </main>


    </div>
  )
}
