import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import NavBar from '../comps/NavBar';
import TopBar from '../comps/TopBar';
import Header from '../comps/Header';
import HistoryArticleCard from '../comps/HistoryArticleCard';
import { PageWrap } from '../comps/SetComps';


export default function Home() {
  return (
    <PageWrap>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>@import url('https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;700&display=swap');</style>

      </Head>

      <PageWrap>
        <TopBar
        backto="/history"/>

        <Header
          h1="Vietnamese"/>
          
        <HistoryArticleCard
            text = "Why is the last name Nguyễn so popular?"
            lang = "Vietnamese"
            where ="/history_article"/>

        <HistoryArticleCard
            text = "How to read the structure of Vietnamese names"
            lang = "Vietnamese"
            articleimg = "/Coco_Chalkboard.svg"/>

        <NavBar
          historybuttoncolor='#FC5F6C'
          historytextcolor='#FC5F6C'
       />

      </PageWrap>

    </PageWrap>
  )
}
