import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import NavBar from '../comps/NavBar';
import TopBar from '../comps/TopBar';
import SearchBar from '../comps/SearchBar';
import Header from '../comps/Header';
import DetailText from '../comps/DetailText';
import HistoryTopicCard from '../comps/HistoryTopicCard';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TopBar/>
        <SearchBar/>
        <Header
          h1="Topics"/>
          
        <HistoryTopicCard/>
        
        <HistoryTopicCard
            lang="Japanese"
            flagimg="/JP_FLAG.svg"
            bgimg="/Coco_Japan_Pattern.svg"/>

        <HistoryTopicCard
            lang="Korean"
            flagimg="/SK_FLAG.svg"
            bgimg="/Coco_SK_Pattern.svg"/>

        <HistoryTopicCard
            lang="Vietnamese"
            flagimg="/VN_FLAG.svg"
            bgimg="/Coco_Vietnamese_Pattern.svg"
            where="/history_vn"/>

        <DetailText
        p="Stay tuned for more"/>

        <NavBar
          historybuttoncolor='#FC5F6C'
          historytextcolor='#FC5F6C'
       />

      </main>

    </div>
  )
}
