import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import HomeCard from '../comps/HomeCard';
import NavBar from '../comps/NavBar';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <HomeCard />
        <HomeCard 
        cardbg="#5C80BC"
        verbcolor="#5C80BC"
        heading="History of Asian Names"
        carddescription="Read history lessons on interesting origins of Asian names."
        verb="Read"/>

        <NavBar />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
