import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { lightTheme, darkTheme } from "../comps/darkmode"
import { useState, useEffect } from 'react';
import { GlobalStyles } from '../comps/globalstyles';
import { ThemeProvider } from "styled-components"


import HomeCard from '../comps/HomeCard';
import NavBar from '../comps/NavBar';
import TopBar from '../comps/TopBar';
import Header from '../comps/Header';
import { PageWrap } from '../comps/SetComps';

export default function Home() {
  const [theme, setTheme] = useState('light');
  const isDarkTheme = theme === "dark";

  
  const themeToggler = () => {
      theme === 'light' ? setTheme('dark') : setTheme('light');
      const updatedTheme = isDarkTheme ? "light" : "dark";
      setTheme(updatedTheme);
      localStorage.setItem("theme", updatedTheme);
  }


  useEffect(() => {
      const savedTheme = localStorage.getItem("theme");
      const prefersDark =
        window.matchMedia &&
        window.matchMedia("(prefers-color-scheme: dark)").matches;
      if (savedTheme && ["dark", "light"].includes(savedTheme)) {
        setTheme(savedTheme);
      } else if (prefersDark) {
        setTheme("dark");
      }
  }, []);


  return (
    <ThemeProvider theme={theme === 'light' ? lightTheme : darkTheme}>
    <GlobalStyles />
    <PageWrap>
      <Head>
        
        <title>Pronunci-Asian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>@import url('https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;700&display=swap');</style>
      </Head>

      <PageWrap>
        <TopBar
        backto="/">
        </TopBar>
        <Header
          h1="Let&apos;s start">
        </Header>
          
        <HomeCard 
        where="/namepage">
          </HomeCard>
        <HomeCard 
        cardbg="#5C80BC"
        verbcolor="#5C80BC"
        heading="History of Asian Names"
        carddescription="Read history lessons on interesting origins of Asian names."
        verb="Read"
        where="/history">
          </HomeCard>

        <NavBar
          homebuttoncolor='#FC5F6C'
          hometextcolor='#FC5F6C'>

          </NavBar>

      </PageWrap>

    </PageWrap>



	</ThemeProvider>
  )
}
